[programs.localnet]
hello_anchor_app = "Deppnq5S8rJxBSwbK8GHwakk4oaRfMFcG4p5SkwfUgRq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/bmstar/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
